export * from './pages/RegistrarVentaPage'
export * from './pages/ConsultarVentasPage'
export * from './pages/DetalleVentaPage'
export * from './services/ventasService'
export * from './services/pagosApi'
export * from './types/ventas.types'
