import type { Cliente } from '../types'

// Datos iniciales de clientes
export const initialClientes: Cliente[] = [
  {
    id: '1',
    idUsuario: 2,
    correo: 'rocky.codes@gmail.com',
    nombre: 'Carlos Roca',
    telefono: '70222222',
    direccion: 'Av. Cristo Redentor, 4to anillo',
    foto: 'rocky.jpg',
    rol: 'cliente',
    estado: 'activo',
    fechaRegistro: '2024-01-15',
  },
  {
    id: '2',
    idUsuario: 5,
    correo: 'coco.user@gmail.com',
    nombre: 'Camila Ríos',
    telefono: '70555555',
    direccion: 'Barrio Equipetrol, Calle Los Jazmines',
    foto: 'coco.jpg',
    rol: 'cliente',
    estado: 'activo',
    fechaRegistro: '2024-02-20',
  },
  {
    id: '3',
    idUsuario: 8,
    correo: 'thor.manager@gmail.com',
    nombre: 'Thiago Méndez',
    telefono: '70888888',
    direccion: 'Av. Banzer, 6to anillo',
    foto: 'thor.jpg',
    rol: 'cliente',
    estado: 'activo',
    fechaRegistro: '2024-03-10',
  },
  {
    id: '4',
    idUsuario: 11,
    correo: 'bella.cliente@gmail.com',
    nombre: 'Isabella García',
    telefono: '70123456',
    direccion: 'Zona Sur, Calle 7',
    foto: 'bella.jpg',
    rol: 'cliente',
    estado: 'inactivo',
    fechaRegistro: '2024-01-25',
  },
  {
    id: '5',
    idUsuario: 12,
    correo: 'max.petlover@gmail.com',
    nombre: 'Maximiliano Paz',
    telefono: '70987654',
    direccion: 'Av. Alemana, entre 3er y 4to anillo',
    foto: 'max.jpg',
    rol: 'cliente',
    estado: 'activo',
    fechaRegistro: '2024-04-05',
  },
  {
    id: '6',
    idUsuario: 13,
    correo: 'luna.mascota@gmail.com',
    nombre: 'Luna Herrera',
    telefono: '70654321',
    direccion: 'Villa 1ro de Mayo, Radial 10',
    foto: 'luna_cliente.jpg',
    rol: 'cliente',
    estado: 'activo',
    fechaRegistro: '2024-03-28',
  },
]