import type { Usuario } from './gestionarUsuarios.types';

export const usuariosMock: Usuario[] = [
  {
    id: 1,
    nombre: 'Carlos García',
    correo: 'carlos.garcia@empresa.com',
    telefono: '70000001',
    departamento: 'Tecnología',
    rol: 'Administrador',
    estado: 'Activo',
    creadoEn: '2024-01-15',
  },
  {
    id: 2,
    nombre: 'María López',
    correo: 'maria.lopez@empresa.com',
    telefono: '70000002',
    departamento: 'Recepción',
    rol: 'Recepcionista',
    estado: 'Activo',
    creadoEn: '2024-02-01',
  },
  {
    id: 3,
    nombre: 'Juan Martínez',
    correo: 'juan.martinez@empresa.com',
    telefono: '70000003',
    departamento: 'Consultorio',
    rol: 'Veterinario',
    estado: 'Activo',
    creadoEn: '2024-02-10',
  },
  {
    id: 4,
    nombre: 'Ana Pérez',
    correo: 'ana.perez@empresa.com',
    telefono: '70000004',
    departamento: 'Laboratorio',
    rol: 'Veterinario',
    estado: 'Inactivo',
    creadoEn: '2024-02-20',
  },
  {
    id: 5,
    nombre: 'Luis Herrera',
    correo: 'luis.herrera@empresa.com',
    telefono: '70000005',
    departamento: 'Caja',
    rol: 'Recepcionista',
    estado: 'Activo',
    creadoEn: '2024-03-01',
  },
];