export const TAG_TYPES = [
  'Auth',
  'User',
  'Clients',
  'Pets',
  'Appointments',
  'Bitacora',
  'Servicios',
  'PreciosServicio',
  'CategoriasServicio',
  'CategoriasProducto',
  'Productos',
  'Proveedores',
  'ClinicalHistory',
  'Veterinarias',
  'Grupos',
  'Permisos',
  'Componentes',
  'Suscripciones',
  'Planes',
  'Especies',
  'Razas',
  'Notifications',
  'Devices',
  'Backup',
  'BackupConfig',
  'InventarioStock',
  'InventarioMovimientos',
  'InventarioPuntos',
  'InventarioDisponibilidad',
  'Pagos',
  'Comprobantes',
  'Adopciones',
  'DashboardKPIs',
] as const

export type TagType = (typeof TAG_TYPES)[number]
