/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ClientRouteImport } from './routes/_client'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as ClientMisReservasRouteImport } from './routes/_client/mis-reservas'
import { Route as ClientMisMascotasRouteImport } from './routes/_client/mis-mascotas'
import { Route as ClientClienteRouteImport } from './routes/_client/cliente'
import { Route as ClientPerfil_MascotaRouteImport } from './routes/_client/Perfil_Mascota'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminBitacoraRouteImport } from './routes/_admin/bitacora'
import { Route as AdminGestionar_UsuariosRouteImport } from './routes/_admin/Gestionar_Usuarios'
import { Route as AdminGestionar_Servicios_Precios_CatalogoRouteImport } from './routes/_admin/Gestionar_Servicios_Precios_Catalogo'
import { Route as AdminGestionar_ReservasRouteImport } from './routes/_admin/Gestionar_Reservas'
import { Route as AdminGestionar_MascotasRouteImport } from './routes/_admin/Gestionar_Mascotas'
import { Route as AdminGestionar_ClientesRouteImport } from './routes/_admin/Gestionar_Clientes'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/_client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const ClientMisReservasRoute = ClientMisReservasRouteImport.update({
  id: '/mis-reservas',
  path: '/mis-reservas',
  getParentRoute: () => ClientRoute,
} as any)
const ClientMisMascotasRoute = ClientMisMascotasRouteImport.update({
  id: '/mis-mascotas',
  path: '/mis-mascotas',
  getParentRoute: () => ClientRoute,
} as any)
const ClientClienteRoute = ClientClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => ClientRoute,
} as any)
const ClientPerfil_MascotaRoute = ClientPerfil_MascotaRouteImport.update({
  id: '/Perfil_Mascota',
  path: '/Perfil_Mascota',
  getParentRoute: () => ClientRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBitacoraRoute = AdminBitacoraRouteImport.update({
  id: '/bitacora',
  path: '/bitacora',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGestionar_UsuariosRoute = AdminGestionar_UsuariosRouteImport.update({
  id: '/Gestionar_Usuarios',
  path: '/Gestionar_Usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGestionar_Servicios_Precios_CatalogoRoute =
  AdminGestionar_Servicios_Precios_CatalogoRouteImport.update({
    id: '/Gestionar_Servicios_Precios_Catalogo',
    path: '/Gestionar_Servicios_Precios_Catalogo',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminGestionar_ReservasRoute = AdminGestionar_ReservasRouteImport.update({
  id: '/Gestionar_Reservas',
  path: '/Gestionar_Reservas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGestionar_MascotasRoute = AdminGestionar_MascotasRouteImport.update({
  id: '/Gestionar_Mascotas',
  path: '/Gestionar_Mascotas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGestionar_ClientesRoute = AdminGestionar_ClientesRouteImport.update({
  id: '/Gestionar_Clientes',
  path: '/Gestionar_Clientes',
  getParentRoute: () => AdminRoute,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/Gestionar_Clientes': typeof AdminGestionar_ClientesRoute
  '/Gestionar_Mascotas': typeof AdminGestionar_MascotasRoute
  '/Gestionar_Reservas': typeof AdminGestionar_ReservasRoute
  '/Gestionar_Servicios_Precios_Catalogo': typeof AdminGestionar_Servicios_Precios_CatalogoRoute
  '/Gestionar_Usuarios': typeof AdminGestionar_UsuariosRoute
  '/bitacora': typeof AdminBitacoraRoute
  '/dashboard': typeof AdminDashboardRoute
  '/Perfil_Mascota': typeof ClientPerfil_MascotaRoute
  '/cliente': typeof ClientClienteRoute
  '/mis-mascotas': typeof ClientMisMascotasRoute
  '/mis-reservas': typeof ClientMisReservasRoute
  '/about': typeof PublicAboutRoute
  '/login': typeof PublicLoginRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/Gestionar_Clientes': typeof AdminGestionar_ClientesRoute
  '/Gestionar_Mascotas': typeof AdminGestionar_MascotasRoute
  '/Gestionar_Reservas': typeof AdminGestionar_ReservasRoute
  '/Gestionar_Servicios_Precios_Catalogo': typeof AdminGestionar_Servicios_Precios_CatalogoRoute
  '/Gestionar_Usuarios': typeof AdminGestionar_UsuariosRoute
  '/bitacora': typeof AdminBitacoraRoute
  '/dashboard': typeof AdminDashboardRoute
  '/Perfil_Mascota': typeof ClientPerfil_MascotaRoute
  '/cliente': typeof ClientClienteRoute
  '/mis-mascotas': typeof ClientMisMascotasRoute
  '/mis-reservas': typeof ClientMisReservasRoute
  '/about': typeof PublicAboutRoute
  '/login': typeof PublicLoginRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_client': typeof ClientRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_admin/Gestionar_Clientes': typeof AdminGestionar_ClientesRoute
  '/_admin/Gestionar_Mascotas': typeof AdminGestionar_MascotasRoute
  '/_admin/Gestionar_Reservas': typeof AdminGestionar_ReservasRoute
  '/_admin/Gestionar_Servicios_Precios_Catalogo': typeof AdminGestionar_Servicios_Precios_CatalogoRoute
  '/_admin/Gestionar_Usuarios': typeof AdminGestionar_UsuariosRoute
  '/_admin/bitacora': typeof AdminBitacoraRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_client/Perfil_Mascota': typeof ClientPerfil_MascotaRoute
  '/_client/cliente': typeof ClientClienteRoute
  '/_client/mis-mascotas': typeof ClientMisMascotasRoute
  '/_client/mis-reservas': typeof ClientMisReservasRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/login': typeof PublicLoginRoute
  '/demo/table': typeof DemoTableRoute
  '/_public/': typeof PublicIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Gestionar_Clientes'
    | '/Gestionar_Mascotas'
    | '/Gestionar_Reservas'
    | '/Gestionar_Servicios_Precios_Catalogo'
    | '/Gestionar_Usuarios'
    | '/bitacora'
    | '/dashboard'
    | '/Perfil_Mascota'
    | '/cliente'
    | '/mis-mascotas'
    | '/mis-reservas'
    | '/about'
    | '/login'
    | '/demo/table'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Gestionar_Clientes'
    | '/Gestionar_Mascotas'
    | '/Gestionar_Reservas'
    | '/Gestionar_Servicios_Precios_Catalogo'
    | '/Gestionar_Usuarios'
    | '/bitacora'
    | '/dashboard'
    | '/Perfil_Mascota'
    | '/cliente'
    | '/mis-mascotas'
    | '/mis-reservas'
    | '/about'
    | '/login'
    | '/demo/table'
    | '/demo/form/address'
    | '/demo/form/simple'
  id:
    | '__root__'
    | '/_admin'
    | '/_client'
    | '/_public'
    | '/_admin/Gestionar_Clientes'
    | '/_admin/Gestionar_Mascotas'
    | '/_admin/Gestionar_Reservas'
    | '/_admin/Gestionar_Servicios_Precios_Catalogo'
    | '/_admin/Gestionar_Usuarios'
    | '/_admin/bitacora'
    | '/_admin/dashboard'
    | '/_client/Perfil_Mascota'
    | '/_client/cliente'
    | '/_client/mis-mascotas'
    | '/_client/mis-reservas'
    | '/_public/about'
    | '/_public/login'
    | '/demo/table'
    | '/_public/'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  DemoTableRoute: typeof DemoTableRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client': {
      id: '/_client'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_client/mis-reservas': {
      id: '/_client/mis-reservas'
      path: '/mis-reservas'
      fullPath: '/mis-reservas'
      preLoaderRoute: typeof ClientMisReservasRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/mis-mascotas': {
      id: '/_client/mis-mascotas'
      path: '/mis-mascotas'
      fullPath: '/mis-mascotas'
      preLoaderRoute: typeof ClientMisMascotasRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/cliente': {
      id: '/_client/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClientClienteRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_client/Perfil_Mascota': {
      id: '/_client/Perfil_Mascota'
      path: '/Perfil_Mascota'
      fullPath: '/Perfil_Mascota'
      preLoaderRoute: typeof ClientPerfil_MascotaRouteImport
      parentRoute: typeof ClientRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/bitacora': {
      id: '/_admin/bitacora'
      path: '/bitacora'
      fullPath: '/bitacora'
      preLoaderRoute: typeof AdminBitacoraRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/Gestionar_Usuarios': {
      id: '/_admin/Gestionar_Usuarios'
      path: '/Gestionar_Usuarios'
      fullPath: '/Gestionar_Usuarios'
      preLoaderRoute: typeof AdminGestionar_UsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/Gestionar_Servicios_Precios_Catalogo': {
      id: '/_admin/Gestionar_Servicios_Precios_Catalogo'
      path: '/Gestionar_Servicios_Precios_Catalogo'
      fullPath: '/Gestionar_Servicios_Precios_Catalogo'
      preLoaderRoute: typeof AdminGestionar_Servicios_Precios_CatalogoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/Gestionar_Reservas': {
      id: '/_admin/Gestionar_Reservas'
      path: '/Gestionar_Reservas'
      fullPath: '/Gestionar_Reservas'
      preLoaderRoute: typeof AdminGestionar_ReservasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/Gestionar_Mascotas': {
      id: '/_admin/Gestionar_Mascotas'
      path: '/Gestionar_Mascotas'
      fullPath: '/Gestionar_Mascotas'
      preLoaderRoute: typeof AdminGestionar_MascotasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/Gestionar_Clientes': {
      id: '/_admin/Gestionar_Clientes'
      path: '/Gestionar_Clientes'
      fullPath: '/Gestionar_Clientes'
      preLoaderRoute: typeof AdminGestionar_ClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminGestionar_ClientesRoute: typeof AdminGestionar_ClientesRoute
  AdminGestionar_MascotasRoute: typeof AdminGestionar_MascotasRoute
  AdminGestionar_ReservasRoute: typeof AdminGestionar_ReservasRoute
  AdminGestionar_Servicios_Precios_CatalogoRoute: typeof AdminGestionar_Servicios_Precios_CatalogoRoute
  AdminGestionar_UsuariosRoute: typeof AdminGestionar_UsuariosRoute
  AdminBitacoraRoute: typeof AdminBitacoraRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGestionar_ClientesRoute: AdminGestionar_ClientesRoute,
  AdminGestionar_MascotasRoute: AdminGestionar_MascotasRoute,
  AdminGestionar_ReservasRoute: AdminGestionar_ReservasRoute,
  AdminGestionar_Servicios_Precios_CatalogoRoute:
    AdminGestionar_Servicios_Precios_CatalogoRoute,
  AdminGestionar_UsuariosRoute: AdminGestionar_UsuariosRoute,
  AdminBitacoraRoute: AdminBitacoraRoute,
  AdminDashboardRoute: AdminDashboardRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientPerfil_MascotaRoute: typeof ClientPerfil_MascotaRoute
  ClientClienteRoute: typeof ClientClienteRoute
  ClientMisMascotasRoute: typeof ClientMisMascotasRoute
  ClientMisReservasRoute: typeof ClientMisReservasRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientPerfil_MascotaRoute: ClientPerfil_MascotaRoute,
  ClientClienteRoute: ClientClienteRoute,
  ClientMisMascotasRoute: ClientMisMascotasRoute,
  ClientMisReservasRoute: ClientMisReservasRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  DemoTableRoute: DemoTableRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
